### ISSUE TITLE
Can't resolve handlers on .Net Core 2.1

### ISSUE THREAD

**Issue by pieteckhart** [generik0/Smooth.IoC.Cqrs#1]
Hi,

I'm both new to DI and CQRS. I've read a lot about them but have never actually practiced them.
To make matters worse I'm also taking my first baby steps in .Net Core using the latest 2.1 version that recently got released.

Okay, so here is my situation:
I have two projects:
- Console (a console application)
- Application (a Class library)

The Console references Application. And both have references to the Smooth.IoC.Cqrs NuGet package.
And Console also references the Smooth.IoC.Cqrs.Tap package.

I've modified AutofacCqrsRegistrationModule slightly replacing Assembly.GetCallingAssembly() with AppDomain.CurrentDomain.GetAssemblies() to make sure it also registers in assemblies other then itself.

Example code:
```

//Console
var builder = new ContainerBuilder();
builder.RegisterModule<AutofacCqrsRegistrationModule>();
var container = builder.Build();


var handler= container.Resolve<ICommandHandler<MyFantasticCommand>>(); //The requested service  XXX has not been registered exception


//Application
public class MyFantasticCommandHandler: Handler, ICommandHandler<MyFantasticCommand>
{
...
}

```
Why are my command handlers not being registered? (the same happens with query handlers)
I Also tried using Windsor but that also did not work.

When i manually register a non generic interface from the application library it does show up in the Component Registry. Also the Dispatchers register just fine.

Am I doing something wrong or is this something .Net Core 2.1 related to (open) generics?

Thanks in advance!

Regards,

Piet Eckhart

**Comment by generik0** [comment]
Hi @pieteckhart 
I use this with aspnetcore and appcore and autofac. It works no issue. Maybe you could they with GetEntryAssembily?

I thibk i also see your issue.
You are trying the resolve without parsing  a model as a parameter. You need to pass a model, otherwise the Factory wont resolve it.
Can you try and see If the container has it as “IsRegistered”?
Also can you breakpoint in the factory? What is it doing?

Please note. The TAP cqrs is not a “real” db based Cqrs. But the threadpool is a queue :-)

**Comment by pieteckhart** [comment]
Hi @generik0,

Thanks for your answer. When I get home I will take a look at it again.

**Comment by pieteckhart** [comment]
Hi @generik0 ,

container.IsRegistered<RegisterPatientCommand>(); returns false.
That was expected because container.ComponentRegistry.Registrations did not include any of my commands.

What did you mean by "You need to pass a model". I thought that in my example the MyFantasticCommand would be the command model and i could resolve to MyFantasticCommand*Handler*. Am I understanding correctly?

Also the constructor of the HandlerFactory is never called during my resolve attempt.

BTW: IQuerySingleHandler<TResult> ResolveSingleQuery<TResult>() was missing in the copy/paste code from the main page so I added that my self.

Thanks

**Comment by generik0** [comment]
Hi @pieteckhart
Sorry, you are right. It should be resolving on 👍 var handler= container.Resolve<ICommandHandler<MyFantasticCommand>>(); 

I have implemented this framework into may projects., It works out of the box. Can you share the sorce code with me, maybe i can debug?

Regards Rik

**Comment by pieteckhart** [comment]
Hi @generik0,

I've shared a private repo with you (on bitbucket.org)

Regards,

Piet

**Comment by generik0** [comment]
Hi @pieteckhart 
Thats Great. I will take a gander tonight :-)

**Comment by generik0** [comment]
HI.. Looks like it the flent registration that is the issue:
![image](https://user-images.githubusercontent.com/2411563/42233512-182f72c2-7ef2-11e8-8730-5cf8670137a4.png)

**Comment by generik0** [comment]
@pieteckhart 
I couldn't write to your repo. BUt it was the registrations in autofac that where the issue. The .AsClosedTypesOf() is a filter so a hnadler needed to be all the types to get registered. I have updated the readme.

I noticed you are connecting to an azure store in the the ctor PatientGateway. I would recommend never initializing adb or anything in a ctor.. Exceptions there will kill your container. and issues are difficult to finde.

BR RIk

**Comment by generik0** [comment]
@pieteckhart BTW. thanks for finding this issue....

**Comment by pieteckhart** [comment]
Hi @generik0,

Thanks! Also for the advice concerning the PatientGateway constructor. It's a work in progress ;)
btw: it's not Azure, I'm using a in memory postgres database (normally used for unit testing) in combination with Marten to provide a Document database. This is all just for learning and combining new techniques.

Regards,

Piet

**Comment by generik0** [comment]
@pieteckhart That great :-)
If you are using a DB, and you need it to work with IoC i can point your to my 
[smooth.ioc.dapper ](https://www.nuget.org/packages/Smooth.IoC.Dapper.Repository.UnitOfWork/)
it has many stars. I use the dbfactory with cqrs all the time. Works very well together!

If you want to use EF7 you can use concept to do the same with.
